"""Add blocks field

Revision ID: 874a92d7816d
Revises: fd8337bc9f2b
Create Date: 2025-04-19 03:42:26.877054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '874a92d7816d'
down_revision: Union[str, None] = 'fd8337bc9f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('blocks', sa.ARRAY(postgresql.JSON(astext_type=sa.Text())), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'blocks')
    op.drop_column('documents', 'theme')
    # ### end Alembic commands ###
