# Build Stage 1

FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

COPY front/ ./

# Install dependencies
RUN npm i

# Build the project
RUN npm run build

# Build Stage 2

FROM node:22-alpine
WORKDIR /app

ARG PORT

# Only `.output` folder is needed from the build stage
COPY --from=build /app/.output/ ./

# Change the port and host
ENV PORT $PORT
ENV HOST 0.0.0.0

EXPOSE $PORT

CMD ["node", "/app/server/index.mjs"]
