# Your backend secrets
[db]
user = "postgres"
password = "postgres"
name = "postgres"
host = "db"
port = 5432

[redis]
port = 6379
host = 'redis'

[rabbitmq]
user = "guest"
password = "guest"
host = "rabbitmq"
port = 5672

[openai]
api_url = "https://llm.rdfai.ru/api/providers/openai/v1/chat/completions"
api_key = "9a49054fe339d4bf09f9a35f0d7169e4f4bfacd4bc4b9594406b3348c89d8558"
gpt_model = "gpt-4o"